version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: SalfordDB
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: hotel-backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: SalfordDB
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: hotel-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
